// PM2 Ecosystem Configuration File
// Generated by Elite Auto Server Setup
// Author: naveed-gung (github.com/naveed-gung)

module.exports = {
  apps: [
    {
      name: 'app',
      script: './index.js',
      instances: 'max',
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3000
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000
      },
      error_file: '/var/log/pm2/app-error.log',
      out_file: '/var/log/pm2/app-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 3000,
      shutdown_with_message: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      cron_restart: '0 0 * * *'
    }
  ]
};
